version: '3.8'

services:
  frontend:
    image: moviesaver-client
    ports:
      - "1500:1500"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:7000/api

  backend:
    image: moviesaver-server
    ports:
      - "7000:7000"

