# Generated by Django 4.2.3 on 2024-07-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermovie_unique_together_and_more'),
        ('users', '0005_delete_userprofile_movies'),
    ]

    operations = [
    ]
