FROM python:3.9-slim


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


WORKDIR /app


COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/


EXPOSE 7000


CMD ["gunicorn", "--bind", "0.0.0.0:7000", "vr_project.wsgi:application"]